##Basics of tensorflow

###TensorFlow is an open-source software library for dataflow programming across a range of tasks. It is a symbolic math library, and is also  used for machine learning applications such as neural networks. (Source: wikipedia)

Below are some codes that might help you to understand basics of tensorflow

In [1]:
#importing tensorflow with alias tf
import tensorflow as tf

C:\Users\sprocks\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [2]:
#declaring two constants a & b and initializing them with values 2 & 3
a = tf.constant(2)
b = tf.constant(3)

c = a+b

sess = tf.Session()
print(sess.run(c))

5


In [10]:
#when defining a constant, you have to give it a value, otherwise it will give you error
d = tf.constant()   #this will raise an error

#update_const = tf.assign(d,e)

TypeError: constant() missing 1 required positional argument: 'value'

In [22]:
d = tf.constant(5)
e = tf.constant(6)
update_const = tf.assign(d,e) #this will also raise an error as constant cant be re assigned

AttributeError: 'Tensor' object has no attribute 'assign'

In [24]:
d = tf.constant(5)
e = tf.constant(6)
print("d: ",d)
print("e: ",e)
d = e #this wont be an error as 'd' is now not the old Tensor. It is now the same tensor as 'e'
print("d: ",d)
print(sess.run(d))

d:  Tensor("Const_22:0", shape=(), dtype=int32)
e:  Tensor("Const_23:0", shape=(), dtype=int32)
d:  Tensor("Const_23:0", shape=(), dtype=int32)
6


In [25]:
g = tf.Variable(1)
h = tf.Variable(2)

update_const = tf.assign(g,h)

In [26]:
print(g)

<tf.Variable 'Variable_7:0' shape=() dtype=int32_ref>


In [27]:
print("Value of a :", sess.run(a))
print("Value of b :",sess.run(b))

Value of a : 2
Value of b : 3


In [28]:
print("Value of c :", sess.run(c))
#print("Value of b :",sess.run(b))

Value of c : 5


In [45]:
#this will be an error as accourding to tensorflow, 'g' is right now uninitialized
print("Value of g :", sess.run(g))


Value of g : 1


In [30]:
#to overcome the above problem, all you have to do is to run these 2 lines of code and you will be good to go
init_op = tf.global_variables_initializer()
sess.run(init_op)

In [31]:
#this will be an error
print("Value of a :", sess.run(g))


Value of a : 1


##Strings

In [33]:
hello = tf.constant("Hello World")
print(sess.run(hello))

b'Hello World'


In [41]:
hi = tf.constant("This is Shiv")
print(hi)
print(sess.run(hi))

new_text = tf.add(hello,hi)  #this is same as new_text = hello+hi
print(sess.run(new_text))

Tensor("Const_31:0", shape=(), dtype=string)
b'This is Shiv'
b'Hello WorldThis is Shiv'


In [44]:
#there was a no space between the joined strings, so we will add one space then join
hello = hello + " "
new_text = tf.add(hello,hi)
print(sess.run(new_text))


b'Hello World  This is Shiv '


##Placeholders
A placeholder is simply a variable that we will assign data to at a later date. It allows us to create our operations and build our computation graph, without needing the data.

In [46]:
#you can see that we are not defining the value of 'a', we are just defining the datatype of it
a = tf.placeholder(tf.float32)


In [47]:
#'b' will be two times the value of 'a', but a is still not having any value, so will assign it later
b = a*2

In [50]:
#feeding a placeholder with a value
#the value of a will be passed as a dictionary
result = sess.run(b, feed_dict={a:3})


#you can pass the values directly also as given below, both will give the same result
#result = sess.run(b, {a:3})

print(result)

6.0


In [51]:
#'b'was just a multiple of a, so if we will pass 'a' as [3,4,5],
#the result will be [6. 8. 10.] as the datatype of 'a' was float32
res = sess.run(b, {a: [3,4,5]})
print(res)

[ 6.  8. 10.]


In [52]:
#this is also another way to pass the values
dictio = {a: [[1,2,3],[4,5,6],[7,8,9]]}
res1 = sess.run(b, dictio)
print(res1)

[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]


In [53]:
#lets deal with more than 2 placeholders
b = tf.placeholder(tf.float32)
c = tf.placeholder(tf.float32)

d = b+c

In [55]:
#again, to give the values to 'b' and 'c', we will pass it using a dictionary
res = sess.run(d, {b: 2, c:3})
print(res)

5.0


In [59]:
#dont forget to close the session because
#A session may own resources, such as tf.Variable.
#It is important to release these resources when they are no longer required.
#for that, call the close() method
sess.close()

RuntimeError: Attempted to use a closed Session.

In [60]:
#after executing the above line of codes, the following code will return an error as there is now no object 'sess'
res = sess.run(hello+hi)
print(res)

RuntimeError: Attempted to use a closed Session.

In [61]:
#another way that is generally used is given below because in this case you dont have to explicitly close the session 

with tf.Session() as sess:
  res = sess.run(hello+hi)
  print(res)

b'Hello World  This is Shiv '


In [62]:
#this will also return an error as the session was closed as the control came out of the loop
print(res)

RuntimeError: Attempted to use a closed Session.