##Basics of tensorflow

###TensorFlow is an open-source software library for dataflow programming across a range of tasks. It is a symbolic math library, and is also  used for machine learning applications such as neural networks. (Source: wikipedia)

Below are some codes that might help you to understand basics of tensorflow

In [0]:

import tensorflow as tf

In [0]:
a = tf.constant(2)
b = tf.constant(3)

c = a+b

sess = tf.Session()
print(sess.run(c))

5


In [0]:
d = tf.constant(5)
e = tf.constant(6)

update_const = tf.assign(d,e)

In [0]:
g = tf.Variable(5)
h = tf.Variable(6)

update_const = tf.assign(g,h)

In [0]:
print(g)

In [0]:
print("Value of a :", sess.run(a))
print("Value of b :",sess.run(b))

In [0]:
print("Value of a :", sess.run(c))
#print("Value of b :",sess.run(b))

In [0]:
#this will be an error
print("Value of a :", sess.run(g))


In [0]:
init_op = tf.global_variables_initializer()
sess.run(init_op)

In [0]:
#this will be an error
print("Value of a :", sess.run(g))


In [0]:
#time is till 34:02
#Youtube timings

Strings

In [0]:
hello = tf.constant("Hello World")
print(sess.run(hello))

In [0]:
hi = tf.constant("This is Shiv")
#new_text = hello+hi
new_text = tf.add(hello,hi)
print(sess.run(new_text))

Placeholders

In [0]:
a = tf.placeholder(tf.float32)

In [0]:
b = a*2

In [0]:
#feeding a placeholder with a value
#result = sess.run(b, feed_dict={a:3})
result = sess.run(b, {a:3})
print(result)

6.0


In [0]:
res = sess.run(b, {a: [3,4,5]})
print(res)

[ 6.  8. 10.]


In [0]:
dictio = {a: [[1,2,3],[4,5,6],[7,8,9]]}
res1 = sess.run(b, dictio)
print(res1)

[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]


In [0]:
sess.close()

In [0]:
with tf.Session() as sess:
  res = sess.run(hello+hi)
  print(res)

b'Hello WorldThis is Shiv'


In [0]:
res = sess.run(hello+hi)
print(res)